Algoritmo "EXERCICIO_SOMA_PARES"

Var

   x, sum : inteiro

Inicio

      escreva("Digite um número inteiro: ")
      leia(x)
      
      enquanto x <> 0 faca
      
         se x % 2 <> 0 entao
         
             x <- x + 1
         
         fimse

             sum <- 5 * x + 20
         
         escreva("Soma = ",sum)
         escreva("Digite um número inteiro: ")
         leia(x)
      
      fimenquanto

Fimalgoritmo
